// Auto-generated heightmaps file
// Generated by tools/generate_heightmaps.py

#ifndef COLLISION_GENERATED_HEIGHTMAPS_H
#define COLLISION_GENERATED_HEIGHTMAPS_H

#include <stdint.h>

#define TILESET_TILE_COUNT 224
#define TILE_WIDTH 16

// Single tileset heightmaps: [tile][column]
extern const int TILESET_HEIGHTMAPS[][TILE_WIDTH];

int* GetTileHeightMap(int tileId);
#endif // COLLISION_GENERATED_HEIGHTMAPS_H
