// Auto-generated widthmaps file
// Generated by tools/generate_heightmaps.py

#ifndef GENERATED_WIDTHMAPS_H
#define GENERATED_WIDTHMAPS_H

#include <stdint.h>

#define TILESET_TILE_COUNT 224
#define TILE_HEIGHT 16

// Single tileset widthmaps: [tile][column]
extern const int TILESET_WIDTHMAPS[][TILE_HEIGHT];

// Tileset name
int* GetTileWidthMap(int tileId);
#endif // GENERATED_WIDTHMAPS_H
