// Auto-generated tile angles file
// Generated by tools/generate_tile_angles.py

#ifndef GENERATED_TILE_ANGLES_H
#define GENERATED_TILE_ANGLES_H

#include <stdint.h>

#define TILESET_TILE_COUNT 224

// Tile angles from heightmaps (floor/ceiling collision)
extern const int TILESET_HEIGHT_ANGLES[];

// Tile angles from widthmaps (wall collision)
extern const int TILESET_WIDTH_ANGLES[];

// Helper to retrieve a tile's precomputed angle (height-based)
uint8_t GetTileAngle(int tileId);

#endif // GENERATED_TILE_ANGLES_H
