#!/usr/bin/env bash
# generate_heightmaps.sh
# Scans a tileset folder for PNGs, splits each into 16x16 tiles, computes a 16-entry heightmap per tile
# and emits a D source file with arrays for use in tile collision.

set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <tileset-folder> <output-d-file>"
  exit 1
fi

TILE_FOLDER="$1"
OUT_FILE="$2"

# Call python with the folder and output path as args
python3 - "$TILE_FOLDER" "$OUT_FILE" <<'PY'
import sys, os
from PIL import Image

TILE_FOLDER = sys.argv[1]
OUT_FILE = sys.argv[2]

def is_solid_pixel(px):
  # px is an (r,g,b,a) tuple
  return px[3] > 16  # alpha threshold

def compute_heightmap(tile_img):
  w, h = tile_img.size
  assert w == 16 and h == 16
  pixels = tile_img.load()
  heights = []
  for x in range(16):
    col_height = 0
    # scan from bottom to top
    for y in range(15, -1, -1):
      if is_solid_pixel(pixels[x, y]):
        col_height += 1
      else:
        # once we hit transparent above, break to count only contiguous solid from bottom
        if col_height > 0:
          break
    heights.append(col_height)
  return heights

def compute_angle(heights):
  # least-squares slope over x=0..15
  n = 16.0
  sx = sum(float(i) for i in range(16))
  sy = sum(float(h) for h in heights)
  sxx = sum(float(i*i) for i in range(16))
  sxy = sum(float(i*heights[i]) for i in range(16))
  denom = (n * sxx - sx * sx)
  slope = 0.0
  if denom != 0.0:
    slope = (n * sxy - sx * sy) / denom
  import math
  angle_rad = math.atan(slope)
  angle_deg = angle_rad * 180.0 / math.pi
  return angle_deg

def process_tileset(path):
  img = Image.open(path).convert('RGBA')
  tw, th = img.size
  tiles_x = tw // 16
  tiles_y = th // 16
  maps = []
  for ty in range(tiles_y):
    for tx in range(tiles_x):
      box = (tx*16, ty*16, tx*16+16, ty*16+16)
      tile = img.crop(box)
      heights = compute_heightmap(tile)
      maps.append(heights)
  # Sanity: ensure we emitted one map per tile in the tileset
  expected = tiles_x * tiles_y
  if len(maps) != expected:
    print('Warning: expected %d tiles for %s but found %d' % (expected, os.path.basename(path), len(maps)))
  # angles will be computed when writing the file using the same maps list
  return maps

def write_d_file(out_path, data):
  with open(out_path, 'w') as f:
    f.write('// Auto-generated heightmaps file\n')
    f.write('// Generated by tools/generate_heightmaps.sh\n\n')
    f.write('module world.generated_heightmaps;\n\n')

    f.write('int[][][] TILESET_HEIGHTMAPS = [\n')
    for ts_name, maps in data.items():
      # write a comment with the tileset name and count
      f.write('    // Tileset: %s (tiles=%d)\n' % (ts_name, len(maps)))
      f.write('    [\n')
      for m in maps:
        f.write('        [' + ', '.join(str(x) for x in m) + '],\n')
      f.write('    ],\n')
    f.write('];\n')

    # Emit tileset names for runtime matching
    f.write('\nstring[] TILESET_NAMES = [\n')
    for ts_name in data.keys():
      f.write('    "%s",\n' % ts_name)
    f.write('];\n')

    # Emit per-tile precomputed ground angles (degrees) as float[][] parallel to heightmaps
    f.write('\nfloat[][] TILESET_GROUND_ANGLES = [\n')
    for ts_name, maps in data.items():
      f.write('    // Tileset: %s\n' % ts_name)
      f.write('    [\n')
      for m in maps:
        angle = compute_angle(m)
        f.write('        %.6ff,\n' % float(angle))
      f.write('    ],\n')
    f.write('];\n')

    # Also emit flipped-variant tables: for each tileset, 8 variants (bits H=1,V=2,D=4)
    # Structure: TILESET_HEIGHTMAPS_VARIANTS[tilesetIdx][variantIdx][tileIdx][col]
    f.write('\nint[][][][] TILESET_HEIGHTMAPS_VARIANTS = [\n')
    for ts_name, maps in data.items():
      f.write('    // Tileset: %s\n' % ts_name)
      f.write('    [\n')
      # prepare variant lists: variantIdx 0..7
      variants = [ [] for _ in range(8) ]
      for m in maps:
        # build occupancy grid for source heights
        src = [ max(0, min(16, int(x))) for x in m ]
        # build occ[y][x] with y from 0 (top) to 15 (bottom): occ[y][x] = (y < src[x])
        occ = [[ (1 if y < src[x] else 0) for x in range(16) ] for y in range(16)]
        # for each variant, compute transformed heights
        for var in range(8):
          hadH = (var & 1) != 0
          hadV = (var & 2) != 0
          hadD = (var & 4) != 0

          occ_t = [row[:] for row in occ]
          h = hadH
          v = hadV
          d = hadD
          if d:
            # transpose
            occ_tt = [[ occ_t[x][y] for x in range(16) ] for y in range(16)]
            occ_t = occ_tt
            # swap h and v
            tmp = h; h = v; v = tmp

          if h:
            occ_h = [ [ occ_t[y][15 - x] for x in range(16) ] for y in range(16) ]
            occ_t = occ_h

          if v:
            occ_v = [ [ occ_t[15 - y][x] for x in range(16) ] for y in range(16) ]
            occ_t = occ_v

          # reconstruct heights per column
          out_heights = []
          for x in range(16):
            cnt = 0
            for y in range(16):
              if occ_t[y][x]: cnt += 1
            if cnt < 0: cnt = 0
            if cnt > 16: cnt = 16
            out_heights.append(cnt)
          variants[var].append(out_heights)

      # write variants for this tileset
      for var in range(8):
        f.write('        [\n')
        for mvar in variants[var]:
          f.write('            [' + ', '.join(str(x) for x in mvar) + '],\n')
        f.write('        ],\n')
      f.write('    ],\n')
    f.write('];\n')

    # Emit per-variant ground angles: TILESET_GROUND_ANGLES_VARIANTS[tilesetIdx][variantIdx][tileIdx]
    f.write('\nfloat[][][] TILESET_GROUND_ANGLES_VARIANTS = [\n')
    for ts_name, maps in data.items():
      f.write('    // Tileset: %s\n' % ts_name)
      f.write('    [\n')
      # compute variants for angles similarly
      variants_angles = [ [] for _ in range(8) ]
      for m in maps:
        src = [ max(0, min(16, int(x))) for x in m ]
        occ = [[ (1 if y < src[x] else 0) for x in range(16) ] for y in range(16)]
        for var in range(8):
          hadH = (var & 1) != 0
          hadV = (var & 2) != 0
          hadD = (var & 4) != 0
          occ_t = [row[:] for row in occ]
          h = hadH
          v = hadV
          d = hadD
          if d:
            occ_tt = [[ occ_t[x][y] for x in range(16) ] for y in range(16)]
            occ_t = occ_tt
            tmp = h; h = v; v = tmp
          if h:
            occ_h = [ [ occ_t[y][15 - x] for x in range(16) ] for y in range(16) ]
            occ_t = occ_h
          if v:
            occ_v = [ [ occ_t[15 - y][x] for x in range(16) ] for y in range(16) ]
            occ_t = occ_v
          # reconstruct heights
          out_heights = []
          for x in range(16):
            cnt = 0
            for y in range(16):
              if occ_t[y][x]: cnt += 1
            out_heights.append(cnt)
          variants_angles[var].append(compute_angle(out_heights))

      for var in range(8):
        f.write('        [\n')
        for ang in variants_angles[var]:
          f.write('            %.6ff,\n' % float(ang))
        f.write('        ],\n')
      f.write('    ],\n')
    f.write('];\n')

def main():
  data = {}
  for root, dirs, files in os.walk(TILE_FOLDER):
    for fn in files:
      if fn.lower().endswith('.png'):
        path = os.path.join(root, fn)
        rel = os.path.relpath(path, TILE_FOLDER)
        name = rel.replace(os.sep, '_')
        print('Processing', path)
        maps = process_tileset(path)
        data[name] = maps
  write_d_file(OUT_FILE, data)

if __name__ == '__main__':
  main()

PY